### ISSUE TITLE
Large operation fails with no error

### ISSUE THREAD

**Issue by azizLIGHT** [tmccoid-tech/extract-em#1]
![Screenshot_20240311_113643__Extract 'Em! - Mozilla Thunderbird Beta_](https://github.com/tmccoid-tech/extract-em/assets/8013867/3c204aeb-430e-4f93-8a7c-fce6bab78a6e)

The save as dialog for the zip file never appears when dealing with a folder of 56k emails with 169k attachments. I have tried smaller folders with success, FYI: the file save dialog apepars and I can save the zip file and see the success message. For the large operation, I have enough disk space, enough memory I think (32 GB total, the Packaging stage depletes 10 GB of ram, the size of the archive). I am guessing the problem is in creating the zip.

Thunderbird Beta 124.0b4 (64-bit) flatpak

**Comment by tmccoid-tech** [comment]
Thank you for reporting this issue.  My suspicion is that you are running against a system limit with regards to maximum .zip file size or maximum number of files which can be included in a .zip file.

If this is immediately urgent for you, I suggest the following:

1) If you already segregate your messages into subfolders, select the Let Me Choose option and extract in multiple batches, selecting subsets of folders which will not result in the error

2) If you do not currently use subfolders, consider creating some based on some meaningful criteria and then implementing filters to move to messages into the associated subfolders

In any event, I will attempt to implement more graceful handling of the error and provide a workaround, such as splitting the results into multiple archives (requiring serial filename prompts, unfortunately).

**Comment by tmccoid-tech** [comment]
It appears that the issue may have been caused by the resulting .zip file size exceeding a limit of 1 GB imposed by Thunderbird for "downloads"; I reproduced the error with a total archive size of just over 1 GB.

I have a fix in the that works that will generate multiple .zip files with contents beneath that threshold (early testing has been successful).  With any luck this will be generally available in the next several days.

**Comment by tmccoid-tech** [comment]
Version 1.1.2 of the extension is currently under review by the Thunderbird extension crew.  Given that a weekend is upon us, this may not be available until next week.

If you would like, you can side-load the extension by doing the following:

1) Download the extension .zip file from [ExtractEm_1.1.2.zip](https://github.com/tmccoid-tech/extract-em/files/14618713/ExtractEm_1.1.2.zip)
2) Select Tools | Add-ons and Themes from the Thunderbird menu
3) Remove version 1.1.1 of Extract 'Em from Thunderbird
4) Select the gear (menu) icon and choose the Install Add-on from File option
5) Select the downloaded .zip file

I set the size limit for individual result files to ~750 MB (the actual limit appears to be 800 MB, but I haven't found anything definitive on this).  Since you have 10 GB of attachments, you will be prompted around 14 times.

In testing, I successfully separated over 1 GB of attachments into two result archives.

Hope this works for you.  Look forward to your feedback.

**Comment by azizLIGHT** [comment]
The zip version worked for me perfectly. I have 169k attachments saved successfully with the 14 save prompts. So, this version solves the issue. Here's some feedback:
- This version does not occupy 10 GB of ram anymore which is excellent. It only takes up to 750 MB per prompt and then drops back to 0 and builds up again to 750 MB for the next archvie. Great work here on optimization and doesn't risk computer going unstable
- File save prompts: Maybe the directory to save in could be specified as an option or default to Downloads directory or asked once and all archives saved there without a prompt

Thanks for the quick fix

**Comment by azizLIGHT** [comment]
It may also be worth adding a grouping by email subject or a textbox where you can specify the grouping structure. For example:
`$author/$date - $subject - $attachmentname.$attachmentext` could be typed in to pick from a defined list of metadata. There's already author, folder, and file extension there

**Comment by tmccoid-tech** [comment]
Glad it worked for you, and thanks for the suggestions.  I will take them into consideration.

Unfortunately the no/single prompt notion doesn't appear to be workable due to security constraints imposed by Thunderbird; however, I will review this and research to see if at least assigning an extension-level default downloads directory is achievable.

Grouping and filename templating are certainly doable.

If you would be so kind, I would appreciate a rating on the extension.

Regards, and thanks again!
