### ISSUE TITLE
Context menu of a single selected message

### ISSUE THREAD

**Issue by Korb** [tmccoid-tech/extract-em#23]
When you activate the extension from the context menu of a message with an attachment, a window is displayed stating:

> Messages: 28704 selected
> w/📎: 0
> Attachments: 0 selected, 0 bytes

This looks like a bug. Expected behavior:

> Messages: 1 selected
> w/📎: 1
> Attachments: 1 selected, ... bytes

Extract 'Em! 1.4.3 (September 10, 2024)
Mozilla Thunderbird 128.2.0esr (64-bit)
Microsoft Windows 10.0.19045.4842

**Comment by tmccoid-tech** [comment]
Hi,

This is actually the correct behavior.

1) When you activate the extension on a single message, the context for the process is the folder that the message resides in, not the message itself.  The extension was developed to handle batch extraction across multiple messages since that functionality is not built into Thunderbird; the ability to save off or detach from a single message is natively available.

2) It appears you are using the Let Me Choose option.  The number of attachments is not immediately known in this case; the extension needs to execute a query to determine which messages within the selected scope have attachments.  The Discover Attachments button accomplishes this.  If you did attempt discovery and still came up with 0 attachments then there likely is a problem and I will need to collect more information from you in order to troubleshoot.

The instructions for Extract 'Em! are located at:
[https://github.com/tmccoid-tech/extract-em/wiki](https://github.com/tmccoid-tech/extract-em/wiki)

**Comment by Korb** [comment]
> It appears you are using the Let Me Choose option.

Do you mean the `Use interactive UI (Fully interactive UI; allows for selection of specific attachments to extract)` option? Yes, it was enabled.

After changing this setting to `Display QuickMenu (Displays a shortcut menu when Extract 'Em! is opened)` when I select `Extract 'Em!` in the context menu of an email, I get a window with two options: `Extract 'Em! (Extracts attachments from the selected folder, omitting sub-folders)` and `Let Me Choose (Allows you to choose specific folders, or even specific attachments for discovery and extraction)`, which made it more obvious to me that this extension is not suitable for my purposes. Sorry for having to create a ticket in "Issues" because discussions are disabled in this repository.
