### ISSUE TITLE
Save attachements in local folder w/o zip

### ISSUE THREAD

**Issue by vinchounz** [tmccoid-tech/extract-em#27]
Hi, I just discovered your extension and it's what I was looking for because the attachments date and time is exactly the ones of the received email.
But I would like just to extract the attachments and copy them into a local folder in which I gather all the attachments without going through a ZIP file. And with the automatic extraction feature on new mails it will be perfect !
So would it be possible to add the feature to only copy attachments to local folder without zipping them in the future ?

**Comment by tmccoid-tech** [comment]
Originally I did not believe this to be possible due to certain restrictions within the extensions API; however, I now believe there may be a way to accomplish this.  It would rely upon the user having selected a specific downloads directory in the Thunderbird settings rather than the Always Prompt Me option; otherwise the user would be prompted for each file, which would be cumbersome to say the least.

There are a couple of technical details I need to work before I can say this absolutely achievable.

**Comment by tmccoid-tech** [comment]
@vinchounz 

I have determined that this can be done and will implement it in the next feature version of Extract 'Em! which I hope to have available by mid-November.

Unfortunately, there is a major catch regarding the directory to which the files will be saved.  Due to limitations of the Thunderbird API, the only directory which an individual file can be saved to without prompting the user is that specified in the Thunderbird settings (the "Save files to" setting in the General | Files & Attachments section).  It is not possible to set this directory specific to the extension, nor is it possible to prompt once prior to saving and have all discovered attachments save to that directory afterwards.  Furthermore, it is not possible to create a subfolder on the fly within that default directory, meaning that if repeated extractions are performed they will always be dumped into that same directory (unless the user changes the Thunderbird setting each time.)  Wish I had better news on that front.

**Comment by vinchounz** [comment]
Hi, good news !
On my side I will be happy with this behavior even if the selection of different subfolders would have been perfect to download attachments from my different accounts.
I can't wait to test !
cheers

**Comment by Dirk123456789** [comment]
I just wanted to add my thanks as well. I've just discovered your extension, and I was wondering the same thing - if it would be possible to extract without zipping.  The default directory setting isn't an issue for me either. :) 
Thanks!

**Comment by tmccoid-tech** [comment]
This feature is now implemented; however, I am not going to publicly release a new version of the extension at this time as I will be traveling shortly.

In the meantime, I have made a version available for side-loading (direct installation):
[https://tmccoid.tech/public/extractem_1_6_0.zip](https://tmccoid.tech/public/extractem_1_6_0.zip)

To side-load:
1) Change the file extension of the downloaded file from .zip to .xpi
2) Select Add-ons and Themes from the Thunderbird Tools menu, click the gear button, and select Install Add-on from File
3) Select the .xpi file
4) If you want to continue receiving updated versions of Extract 'Em!, click the wrench button for the extension, and on the Details tab set the Allow automatic updates value to On

To activate the new feature, in the extension Options select  Save individual attachments under the Storage Options section

![image](https://github.com/user-attachments/assets/8aa115a1-0bcd-427b-b94e-bb09d478ea07)

Please let me know if you have any questions or issues.  I look forward to hearing your feedback, and if you have a moment I would appreciate if you could provide a review on the Thunderbird Add-ons site.

Tom

**Comment by tmccoid-tech** [comment]
Unfortunately, setting the file creation or modification timestamp is not supported in this case; it is a limitation of the save mechanism provided through the Thunderbird API and there is no way around it.

What I might suggest is using the filename pattern feature to append the date/time to the filename, thus giving you the identifying info you require.

Closing this issue as the feature is otherwise implemented in v. 1.6.1
