### ISSUE TITLE
Attachments in some e-mails don’t get saved

### ISSUE THREAD

**Issue by SmilingGit** [tmccoid-tech/extract-em#28]
Hi there,

Thank you for this very useful extension. I had it run on a folder with smaller and larger attachments (some over 30 MB), and unfortunately, Extract 'Em! didn’t touch some e-mails (didn’t extract the attachments, and therefore didn’t detach them). I even isolated the messages in a separate folder and had it run on them only, but somehow it didn’t detect that there were attachments in them. The emails were rather old, if I remember right. The inbuilt function of TB to detach the attachments worked. I tried Extract 'Em! with and without the inline setting (the attachments were not inline, but you never know). I couldn’t find out what the emails had in common that prevented Extract 'Em! from working.

Have a great day!

**Comment by tmccoid-tech** [comment]
Hi,
Sorry that you are having trouble with the extension.  I can assist if you can do the following:

1) Let me know the version of Extract 'Em! and Thunderbird you are using
2) Send me at least one of the emails which contains an attachment (preferably a smaller one since size limits are now common) which is not being identified; rather than forward the .eml file(s), please package in a .zip file and send that to extractem-dev@tmccoid.tech

Similar problems have been previously reported with older emails which sometimes have unusual message structures.

Regards,
Tom

**Comment by tmccoid-tech** [comment]
I believe that this issue has been resolved with the release of version 1.6.2; in short, certain attachments were incorrectly being identified as embeds, but as they were not embeds could not be extracted by the pertinent logic.

**Comment by SmilingGit** [comment]
Wonderful, thank you very much! I’m so sorry I didn’t answer to your previous message, I got so busy in the meantime and then I forgot. 
I wish you a wonderful end of year and all the best!

**Comment by jbrokamp** [comment]
Thank you for fixing this, I noticed this myself since 1.6.1.
